### PR TITLE
Enable the esModuleInterop compiler flag and address compiler warnings

### PR DESCRIPTION
**Pull request by AlexGhiondea**
Enable the esModuleInterop compiler option to emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports.

Addressing the compiler errors that showed up after that change.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
Anybody redeploying their application that uses the event-hubs sdk, will end up getting this new version of `amqp-common`. 

I tried to mimic this scenario by doing the below:
- Updated the package.json of the `client` in the event-hubs repo to use this branch of `amqp-common`
- Ran `npm install`
- Ran `npm run build`. The `tsc` step at this point fails with the below

image

- Created a test application that uses the event-hubs sdk. Instead of adding the sdk as a dependency, I used  [npm link](https://docs.npmjs.com/cli/link.html) to use my local version of the sdk
- Ran `tsc` on this test application to generate the .js file which runs without errors

**Comment by AlexGhiondea** [comment]
Does the version that the package has matter? 

It also sounds like you get an error while building the event hubs SDK, right?

**Comment by AlexGhiondea** [comment]
So we are forced to change the major? We can't just change minor?

The only way we can change major is to go from 0->1 which I was hoping to avoid.

**Comment by ramya-rao-a** [comment]
**Update**:

Adding `"esModuleInterop": true` to event hubs fixes the error from tsc mentioned in https://github.com/Azure/amqp-common-js/pull/16#issuecomment-452952680

I'll run the tests in the event hubs repo with the above change


> The only way we can change major is to go from 0->1 which I was hoping to avoid.

I dont see any other way to ensure that we break no customers of amqp-common and event-hubs

**Comment by ramya-rao-a** [comment]
Some tests in event hubs do fail, but they also fail with the latest version of the `amqp-common` library. See https://github.com/Azure/azure-event-hubs-node/issues/179

All green to publish this change as 1.0.0

**Comment by AlexGhiondea** [comment]
Are you saying we should fix/merge the tests in Event Hub first, before merging this PR?

**Comment by ramya-rao-a** [comment]
No, we can merge this PR.

I was talking about fixing the tests before publishing a 1.0.0 of amqp-common.
Chances are that the fixes would be in amqp-common.
In which case, it would be nice to not publish 1.0.0 with bugs :)

**Comment by ramya-rao-a** [comment]
Sure

**Pull request merged**
